"""Add event models

Revision ID: 02411897f536
Revises: 3549700aa31e
Create Date: 2025-05-20 15:09:54.148104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02411897f536'
down_revision = '3549700aa31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
